#lang racket
; Symbol -> Name -> Atomic Number -> Atomic Weight
(define elements
  (list (list 
         "H"
         "Hydrogen"
         1
         1.0079)
        (list
         "He"
         "Helium"
         2
         4.0026
         )
        (list
         "Li"
         "Lithium"
         3
         6.941
         )
        (list
         "Be"
         "Beryllium"
         4
         9.0122
         )
        (list
         "B"
         "Boron"
         5
         10.811
         )
        (list
         "C"
         "Carbon"
         6
         12.011
         )
        (list
         "N"
         "Nitrogen"
         7
         14.007)
        (list
         "O"
         "Oxygen"
         8
         15.999
         )
        (list
         "F"
         "Fluorine"
         9
         18.998)
        (list
         "Ne"
         "Neon"
         10
         20.180)
        (list
         "Na"
         "Sodium"
         11
         22.990)
        (list
         "Mg"
         "Magnesium"
         12
         24.305)
        (list
         "Al"
         "Aluminium"
         13
         26.982
         )
        (list
         "Si"
         "Silicon"
         14
         28.086)
        (list
         "P"
         "Phosphorus"
         15
         30.974)
        (list
         "S"
         "Sulfur"
         16
         32.066)
        (list
         "Cl"
         "Chlorine"
         17
         35.453)
        (list
         "Ar"
         "Argon"
         18
         39.948)
        (list
         "K"
         "Potassium"
         19
         39.098)
        (list
         "Ca"
         "Calcium"
         20
         40.078)
        (list
         "Sc"
         "Scandium"
         21
         44.956)
        (list
         "Ti"
         "Titanium"
         22
         47.876)
        (list
         "V"
         "Vanadium"
         23
         50.942)
        (list
         "Cr"
         "Chromium"
         24
         51.996)
        (list
         "Mn"
         "Manganese"
         25
         54.938)
        (list
         "Fe"
         "Iron"
         26
         55.845)
        (list
         "Co"
         "Cobalt"
         27
         58.933)
        (list
         "Ni"
         "Nickel"
         28
         58.693)
        (list
         "Cu"
         "Copper"
         29
         63.546)
        (list
         "Zn"
         "Zinc"
         30
         65.39)
        (list
         "Ga"
         "Gallium"
         31
         69.723)
        (list
         "Ge"
         "Germanium"
         32
         72.61)
        (list
         "As"
         "Arsenic"
         33
         74.922)
        (list
         "Se"
         "Selenium"
         34
         78.96)
        (list
         "Br"
         "Bromine"
         35
         79.904)
        (list
         "Kr"
         "Krypton"
         36
         83.80)
        (list
         "Rb"
         "Rubidum"
         37
         85.468)
        (list
         "Sr"
         "Strontium"
         38
         87.62)
        (list
         "Y"
         "Yttrium"
         39
         88.906)
        (list
         "Zr"
         "Zirconium"
         40
         91.224)
        (list
         "Nb"
         "Niobium"
         41
         92.906)
        (list
         "Mo"
         "Molybdenum"
         42
         95.94)
        (list
         "Tc"
         "Technetium"
         43
         97.907)
        (list
         "Ru"
         "Ruthenium"
         44
         101.07)
        (list
         "Rh"
         "Rhodium"
         45
         102.91)
        (list
         "Pd"
         "Palladium"
         46
         106.42)
        (list
         "Ag"
         "Silver"
         47
         107.87)
        (list
         "Cd"
         "Cadmium"
         48
         112.41)
        (list
         "In"
         "Indium"
         49
         114.82)
        (list
         "Sn"
         "Tin"
         50
         118.71)
        (list
         "Sb"
         "Antimony"
         51
         121.76)
        (list
         "Te"
         "Tellurium"
         52
         127.60)
        (list
         "I"
         "Iodine"
         53
         126.90)
        (list
         "Xe"
         "Xenon"
         54
         131.29
         )
        (list
         "Cs"
         "Caesium"
         55
         132.91)
        (list
         "Ba"
         "Barium"
         56
         137.33)
        (list
         "La"
         "Lanthanum"
         57
         138.9055)
        (list
         "Ce"
         "Cerium"
         58
         140.12)
        (list
         "Pr"
         "Praseodymium"
         59
         140.91)
        (list
         "Nd"
         "Neodymium"
         60
         144.24)
        (list
         "Pm"
         "Promethium"
         61
         144.91)
        (list
         "Sm"
         "Samarium"
         62
         150.36)
        (list
         "Eu"
         "Europium"
         63
         150.36)
        (list
         "Gd"
         "Gadolinium"
         64
         157.25)
        (list
         "Tb"
         "Terbium"
         65
         158.93)
        (list
         "Dy"
         "Dysprosium"
         66
         162.50)
        (list
         "Ho"
         "Holmium"
         67
         164.93)
        (list
         "Er"
         "Erbium"
         68
         167.26)
        (list
         "Tm"
         "Thulium"
         69
         168.93)
        (list
         "Yb"
         "Ytterbium"
         70
         173.04)
        (list
         "Lu"
         "Lutetium"
         71
         174.94)
        (list
         "Hf"
         "Hafnium"
         72
         178.49)
        (list
         "Ta"
         "Tantalum"
         73
         180.95)
        (list
         "W"
         "Tungsten"
         74
         183.84)
        (list
         "Re"
         "Rhenium"
         75
         186.21)
        (list
         "Os"
         "Osmium"
         76
         190.23)
        (list
         "Ir"
         "Iridium"
         77
         192.22)
        (list
         "Pt"
         "Platinum"
         78
         195.08)
        (list
         "Au"
         "Gold"
         79
         196.97)
        (list
         "Hg"
         "Mercury"
         80
         200.59)
        (list
         "Tl"
         "Thallium"
         81
         204.38)
        (list
         "Pb"
         "Lead"
         82
         207.2)
        (list
         "Bi"
         "Bismuth"
         83
         208.98)
        (list
         "Po"
         "Polonim"
         84
         208.98)
        (list
         "At"
         "Astatine"
         85
         209.99)
        (list
         "Rn"
         "Radon"
         86
         222.02)
        (list
         "Fr"
         "Francium"
         87
         223.02)
        (list
         "Ra"
         "Radium"
         88
         226.03)
        (list
         "Ac"
         "Actinium"
         89
         227.03)
        (list
         "Th"
         "Thorium"
         90
         232.04)
        (list
         "Pa"
         "Protoactinium"
         91
         231.04)
        (list
         "U"
         "Uranium"
         92
         238.03)
        (list
         "Np"
         "Neptunium"
         93
         237.05)
        (list
         "Pu"
         "Plutonium"
         94
         244.06)
        (list
         "Am"
         "Americium"
         95
         243.06)
        (list
         "Cm"
         "Curium"
         96
         247.07)
        (list
         "Bk"
         "Berkelium"
         97
         247.07)
        (list
         "Cf"
         "Californium"
         98
         251.08)
        (list
         "Es"
         "Einsteinium"
         99
         252.08)
        (list
         "Fm"
         "Fermium"
         100
         257.10)
        (list
         "Md"
         "Mendelevium"
         101
         258.10)
        (list
         "No"
         "Nobelium"
         102
         259.10)
        (list
         "Lr"
         "Lawrencium"
         103
         262.11)
        (list
         "Rf"
         "Rutherfordium"
         104
         261.1)
        (list
         "Db"
         "Dubnium"
         105
         262.11)
        (list
         "Sg"
         "Seaborgium"
         106
         263.1)
        (list
         "Bh"
         "Bohrium"
         107
         264.12)
        (list
         "Hs"
         "Hassium"
         108
         265.1)
        (list
         "Mt"
         "Meitnerium"
         109
         268.14)              
  )
)
;Takes number of protons or atomic number
;returns string
(define (element-name n)
  (car (cdr (list-ref elements (- n 1)))))
;Takes Atomic Number
;Returns Molar Mass
(define (element-mass n)
  (car (cdr (cdr (cdr (list-ref elements (- n 1)))))))

;Takes Atomic Number
;Returns String of the Atomic Symbol
(define (element-symbol n)
  (car (list-ref elements (- n 1))))

;Takes Atomic Symbol
;Returns Atomic Mass
(define (atomic-number-by-symbol sym)
  (fetch-by-symbol elements sym)
  )
;Takes list to be iterated over and the atomic symbol string
;Returns Integer value for atomic number
(define (fetch-by-symbol list sym)
  (if (equal? (car (car list)) sym)
      (car (cdr (cdr (car list))))
      (fetch-by-symbol (cdr list) sym)
      ))
;Takes Atomic Element Name
;Returns Integer value for atomic number
(define (atomic-number-by-name name)
  (fetch-by-name elements name))
;Takes List of elements and name
;Returns Atomic Number
(define (fetch-by-name list name)
  (if (equal? (car (cdr (car list))) name)
      (car (cdr (cdr (car list))))
      (fetch-by-name (cdr list) name)))